<?php

function getSupportedLanguages() {
    return [
        "en" => "English",
        "vi" => "Tiếng Việt"
    ];
}

function isSupportedLanguage($language) {
    return array_key_exists($language, getSupportedLanguages());
}

function setCurrentLanguage($language) {
    $_SESSION["siteLanguage"] = isSupportedLanguage($language) ? $language : "en";
}

function getCurrentLanguage() {
    $language = $_SESSION["siteLanguage"] ?? "en";

    if(!isSupportedLanguage($language)) {
        $language = "en";
        $_SESSION["siteLanguage"] = $language;
    }

    return $language;
}

function getLanguageNativeName($language = null) {
    $language = $language ?? getCurrentLanguage();
    $languages = getSupportedLanguages();

    return $languages[$language] ?? $languages["en"];
}

function t($key, $replace = []) {
    static $translations = [
        "en" => [
            "site.title" => "CineBox",
            "nav.menu" => "Menu",
            "nav.home" => "Home",
            "nav.tv_shows" => "TV Shows",
            "nav.movies" => "Movies",
            "nav.search" => "Search",
            "nav.wishlist" => "Wishlist",
            "nav.profile" => "Profile",
            "nav.logout" => "Log out",
            "wishlist.my" => "My Wishlist",
            "wishlist.open_page" => "Open page",
            "wishlist.empty" => "Your wishlist is empty.",
            "wishlist.empty_hint" => "Add titles from the preview button to see them here.",
            "wishlist.login_required" => "Log in to use your wishlist.",
            "wishlist.empty_page" => "You haven't added any movies to your wishlist yet.",
            "footer.questions" => "Questions?",
            "footer.contact_us" => "Contact us.",
            "footer.faq" => "FAQ",
            "footer.help_centre" => "Help Centre",
            "footer.account" => "Account",
            "footer.media_centre" => "Media Centre",
            "footer.investor_relations" => "Investor Relations",
            "footer.jobs" => "Jobs",
            "footer.ways_to_watch" => "Ways to Watch",
            "footer.terms" => "Terms of Use",
            "footer.privacy" => "Privacy",
            "footer.cookie_preferences" => "Cookie Preferences",
            "footer.corporate_information" => "Corporate Information",
            "footer.speed_test" => "Speed Test",
            "footer.legal_notices" => "Legal Notices",
            "footer.only_on_cinebox" => "Only on CineBox",
            "footer.country" => "CineBox Vietnam",
            "footer.captcha" => "This page is protected by Google reCAPTCHA to ensure you're not a bot.",
            "footer.learn_more" => "Learn more.",
            "language.english" => "English",
            "language.vietnamese" => "Tiếng Việt",
            "search.placeholder" => "Search for something",
            "search.results" => "Search results",
            "watch.back" => "Back",
            "watch.up_next" => "Up next:",
            "watch.next" => "Next",
            "watch.you_might_like" => "You might also like",
            "entity.rate_title" => "Rate this title",
            "entity.your_rating" => "Your rating:",
            "entity.community_rating" => "Community rating:",
            "entity.not_rated" => "Not rated yet",
            "entity.no_ratings" => "No ratings yet",
            "entity.similar_titles" => "Similar titles",
            "entity.rate_star" => "Rate :count star",
            "entity.rate_star_plural" => "Rate :count stars",
            "entity.login_to_rate" => "Log in to rate",
            "profile.welcome" => "Welcome, :name",
            "profile.subscription" => "Subscription",
            "profile.user_details" => "User details",
            "profile.first_name" => "First name",
            "profile.last_name" => "Last name",
            "profile.email" => "Email",
            "profile.gender" => "Gender",
            "profile.username" => "Username",
            "profile.save_details" => "Save details",
            "profile.update_password" => "Update password",
            "profile.old_password" => "Old password",
            "profile.new_password" => "New password",
            "profile.confirm_new_password" => "Confirm new password",
            "profile.change_password" => "Change password",
            "profile.details_saved" => "Details saved",
            "profile.password_changed" => "Password changed",
            "profile.your_first_name" => "Your first name",
            "profile.your_last_name" => "Your last name",
            "profile.your_email" => "Your email",
            "auth.return_world" => "RETURN TO THE WORLD OF",
            "auth.step_world" => "STEP INTO THE WORLD OF",
            "auth.watch_all_in_one" => "Watch trailers, movies and series in one place.",
            "auth.login" => "Log in",
            "auth.signup" => "Sign Up",
            "auth.continue_to_cinebox" => "to continue to CineBox",
            "auth.username" => "Username",
            "auth.password" => "Password",
            "auth.need_account" => "Need an account?",
            "auth.sign_up_here" => "Sign up here!",
            "auth.login_button" => "LOG IN",
            "auth.first_name" => "First name",
            "auth.last_name" => "Last name",
            "auth.confirm_email" => "Confirm email",
            "auth.select_gender" => "Select gender",
            "auth.male" => "Male",
            "auth.female" => "Female",
            "auth.other" => "Other",
            "auth.prefer_not_to_say" => "Prefer not to say",
            "auth.confirm_password" => "Confirm password",
            "auth.already_have_account" => "Already have an account?",
            "auth.log_in_here" => "Log in here!",
            "auth.sign_up_button" => "SIGN UP",
            "preview.continue_watching" => "Continue",
            "preview.play" => "Play",
            "preview.add_to_wishlist" => "Add to wishlist",
            "preview.remove_from_wishlist" => "Remove from wishlist",
            "preview.no_tv_shows" => "No TV shows to display",
            "preview.no_movies" => "No movies to display",
            "category.because_you_watched" => "Because you watched :title",
            "category.tv_shows_heading" => "TV Shows",
            "category.movies_heading" => "Movies",
            "season.title" => "Season :season",
            "season.episode" => "Episode :episode",
            "season.watched" => "Watched",
            "video.season_episode" => "Season :season, Episode :episode",
            "error.no_category_id" => "No id passed to page",
            "error.no_entity_id" => "No ID passed into page",
            "error.video_not_found" => "Video not found",
            "error.first_name_characters" => "Your first name must be between 2 and 25 characters",
            "error.last_name_characters" => "Your last name must be between 2 and 25 characters",
            "error.username_characters" => "Your username must be between 5 and 25 characters",
            "error.username_taken" => "Your username already on use",
            "error.emails_dont_match" => "Your emails don't match",
            "error.email_invalid" => "Invalid email",
            "error.email_taken" => "Email already in use",
            "error.gender_invalid" => "Please select a valid gender",
            "error.passwords_dont_match" => "Your passwords don't match",
            "error.password_length" => "Your password must be between 5 and 25 characters",
            "error.login_failed" => "Your username or password was incorrect",
            "error.password_incorrect" => "Your old password was incorrect",
            "js.wishlist_remove_error" => "Unable to remove this movie from your wishlist right now.",
            "js.wishlist_add_error" => "Unable to add this movie to your wishlist right now.",
            "js.rating_save_error" => "Unable to save your rating right now.",
            "js.wishlist_empty" => "You haven't added any movies to your wishlist yet."
        ],
        "vi" => [
            "site.title" => "CineBox",
            "nav.menu" => "Menu",
            "nav.home" => "Trang chủ",
            "nav.tv_shows" => "Phim bộ",
            "nav.movies" => "Phim lẻ",
            "nav.search" => "Tìm kiếm",
            "nav.wishlist" => "Yêu thích",
            "nav.profile" => "Hồ sơ",
            "nav.logout" => "Đăng xuất",
            "wishlist.my" => "Danh sách yêu thích",
            "wishlist.open_page" => "Mở trang",
            "wishlist.empty" => "Danh sách yêu thích của bạn đang trống.",
            "wishlist.empty_hint" => "Hãy thêm phim từ nút preview để chúng xuất hiện ở đây.",
            "wishlist.login_required" => "Hãy đăng nhập để dùng danh sách yêu thích.",
            "wishlist.empty_page" => "Bạn chưa thêm bộ phim nào vào danh sách yêu thích.",
            "footer.questions" => "Bạn cần hỗ trợ?",
            "footer.contact_us" => "Liên hệ với chúng tôi.",
            "footer.faq" => "Câu hỏi thường gặp",
            "footer.help_centre" => "Trung tâm trợ giúp",
            "footer.account" => "Tài khoản",
            "footer.media_centre" => "Trung tâm truyền thông",
            "footer.investor_relations" => "Quan hệ nhà đầu tư",
            "footer.jobs" => "Việc làm",
            "footer.ways_to_watch" => "Cách xem",
            "footer.terms" => "Điều khoản sử dụng",
            "footer.privacy" => "Quyền riêng tư",
            "footer.cookie_preferences" => "Tùy chọn cookie",
            "footer.corporate_information" => "Thông tin doanh nghiệp",
            "footer.speed_test" => "Kiểm tra tốc độ",
            "footer.legal_notices" => "Thông báo pháp lý",
            "footer.only_on_cinebox" => "Chỉ có trên CineBox",
            "footer.country" => "CineBox Việt Nam",
            "footer.captcha" => "Trang này được Google reCAPTCHA bảo vệ để đảm bảo bạn không phải là robot.",
            "footer.learn_more" => "Tìm hiểu thêm.",
            "language.english" => "English",
            "language.vietnamese" => "Tiếng Việt",
            "search.placeholder" => "Tìm phim hoặc chương trình",
            "search.results" => "Kết quả tìm kiếm",
            "watch.back" => "Quay lại",
            "watch.up_next" => "Tiếp theo:",
            "watch.next" => "Xem tiếp",
            "watch.you_might_like" => "Có thể bạn cũng thích",
            "entity.rate_title" => "Đánh giá tiêu đề này",
            "entity.your_rating" => "Đánh giá của bạn:",
            "entity.community_rating" => "Đánh giá cộng đồng:",
            "entity.not_rated" => "Chưa đánh giá",
            "entity.no_ratings" => "Chưa có đánh giá",
            "entity.similar_titles" => "Tiêu đề tương tự",
            "entity.rate_star" => "Đánh giá :count sao",
            "entity.rate_star_plural" => "Đánh giá :count sao",
            "entity.login_to_rate" => "Đăng nhập để đánh giá",
            "profile.welcome" => "Xin chào, :name",
            "profile.subscription" => "Gói dịch vụ",
            "profile.user_details" => "Thông tin người dùng",
            "profile.first_name" => "Tên",
            "profile.last_name" => "Họ",
            "profile.email" => "Email",
            "profile.gender" => "Giới tính",
            "profile.username" => "Tên đăng nhập",
            "profile.save_details" => "Lưu thông tin",
            "profile.update_password" => "Đổi mật khẩu",
            "profile.old_password" => "Mật khẩu cũ",
            "profile.new_password" => "Mật khẩu mới",
            "profile.confirm_new_password" => "Xác nhận mật khẩu mới",
            "profile.change_password" => "Đổi mật khẩu",
            "profile.details_saved" => "Đã lưu thông tin",
            "profile.password_changed" => "Đã đổi mật khẩu",
            "profile.your_first_name" => "Tên của bạn",
            "profile.your_last_name" => "Họ của bạn",
            "profile.your_email" => "Email của bạn",
            "auth.return_world" => "TRỞ LẠI THẾ GIỚI CỦA",
            "auth.step_world" => "BƯỚC VÀO THẾ GIỚI CỦA",
            "auth.watch_all_in_one" => "Xem trailer, phim lẻ và phim bộ trong cùng một nơi.",
            "auth.login" => "Đăng nhập",
            "auth.signup" => "Đăng ký",
            "auth.continue_to_cinebox" => "để tiếp tục đến CineBox",
            "auth.username" => "Tên đăng nhập",
            "auth.password" => "Mật khẩu",
            "auth.need_account" => "Chưa có tài khoản?",
            "auth.sign_up_here" => "Đăng ký tại đây!",
            "auth.login_button" => "ĐĂNG NHẬP",
            "auth.first_name" => "Tên",
            "auth.last_name" => "Họ",
            "auth.confirm_email" => "Xác nhận email",
            "auth.select_gender" => "Chọn giới tính",
            "auth.male" => "Nam",
            "auth.female" => "Nữ",
            "auth.other" => "Khác",
            "auth.prefer_not_to_say" => "Không muốn tiết lộ",
            "auth.confirm_password" => "Xác nhận mật khẩu",
            "auth.already_have_account" => "Đã có tài khoản?",
            "auth.log_in_here" => "Đăng nhập tại đây!",
            "auth.sign_up_button" => "ĐĂNG KÝ",
            "preview.continue_watching" => "Xem tiếp",
            "preview.play" => "Phát",
            "preview.add_to_wishlist" => "Thêm vào yêu thích",
            "preview.remove_from_wishlist" => "Xóa khỏi yêu thích",
            "preview.no_tv_shows" => "Không có phim bộ để hiển thị",
            "preview.no_movies" => "Không có phim để hiển thị",
            "category.because_you_watched" => "Vì bạn đã xem :title",
            "category.tv_shows_heading" => "Phim bộ",
            "category.movies_heading" => "Phim lẻ",
            "season.title" => "Mùa :season",
            "season.episode" => "Tập :episode",
            "season.watched" => "Đã xem",
            "video.season_episode" => "Mùa :season, Tập :episode",
            "error.no_category_id" => "Không có id được truyền vào trang",
            "error.no_entity_id" => "Không có ID được truyền vào trang",
            "error.video_not_found" => "Không tìm thấy video",
            "error.first_name_characters" => "Tên của bạn phải dài từ 2 đến 25 ký tự",
            "error.last_name_characters" => "Họ của bạn phải dài từ 2 đến 25 ký tự",
            "error.username_characters" => "Tên đăng nhập phải dài từ 5 đến 25 ký tự",
            "error.username_taken" => "Tên đăng nhập đã được sử dụng",
            "error.emails_dont_match" => "Hai email không khớp nhau",
            "error.email_invalid" => "Email không hợp lệ",
            "error.email_taken" => "Email đã được sử dụng",
            "error.gender_invalid" => "Vui lòng chọn giới tính hợp lệ",
            "error.passwords_dont_match" => "Hai mật khẩu không khớp nhau",
            "error.password_length" => "Mật khẩu phải dài từ 5 đến 25 ký tự",
            "error.login_failed" => "Tên đăng nhập hoặc mật khẩu không đúng",
            "error.password_incorrect" => "Mật khẩu cũ không đúng",
            "js.wishlist_remove_error" => "Hiện không thể xóa phim này khỏi danh sách yêu thích.",
            "js.wishlist_add_error" => "Hiện không thể thêm phim này vào danh sách yêu thích.",
            "js.rating_save_error" => "Hiện không thể lưu đánh giá của bạn.",
            "js.wishlist_empty" => "Bạn chưa thêm bộ phim nào vào danh sách yêu thích."
        ]
    ];

    $language = getCurrentLanguage();
    $text = $translations[$language][$key] ?? $translations["en"][$key] ?? $key;

    foreach($replace as $name => $value) {
        $text = str_replace(":" . $name, (string)$value, $text);
    }

    return $text;
}
